// Generated by update-system-info.sh
var os_age_seconds = "5111737";
var cpu = "AMD Ryzen 5 7600";
var hostname = "WOLKOON";
var kernel = "7.1.3-2-CACHYOS";
var os = "CACHYOS";
var architecture = "X86_64";
