#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
THEME="$(dirname "$SCRIPT_DIR")"

echo "// Generated by update-system-info.sh" > "$THEME/utils/SystemInfo.js"
echo "var os_age_seconds = \"$(./osAgeSeconds.sh)\";" >> "$THEME/utils/SystemInfo.js"
echo "var cpu = \"$(./cpu.sh)\";" >> "$THEME/utils/SystemInfo.js"
echo "var hostname = \"$(./hostname.sh)\";" >> "$THEME/utils/SystemInfo.js"
echo "var kernel = \"$(./kernel.sh)\";" >> "$THEME/utils/SystemInfo.js"
echo "var os = \"$(./os.sh)\";" >> "$THEME/utils/SystemInfo.js"
echo "var architecture = \"$(./architecture.sh)\";" >> "$THEME/utils/SystemInfo.js"